eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: solventa-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:8001 #lb://msvc-course # lb://msvc-student
          predicates:
            - Path=/api/solventa/user/**
        - id: device
          uri: http://localhost:8002 #lb://msvc-course # lb://msvc-student
          predicates:
            - Path=/api/solventa/device/**
        - id: booking
          uri: http://localhost:8003 #lb://msvc-course # lb://msvc-student
          predicates:
            - Path=/api/solventa/booking/**